function hp = fixed_hp(epochs)
% AJSE_ICNN.FIXED_HP  Frozen v4 I-CNN architecture, without new tuning.
if nargin<1 || isempty(epochs); epochs=200; end
hp=struct('kernels',[3 5 7], ...
    'filters',32, ...
    'lr',1e-4, ...
    'epochs',epochs, ...
    'batch',32, ...
    'window',16, ...
    'selection_status','FROZEN_FROM_PREDECESSOR_ARCHITECTURE', ...
    'wellB_used_for_tuning',false);
end
