function generate_captions(bundle, fig_status)
run=bundle.run; cfg=bundle.cfg_fig; out=bundle.out;
lines={};
lines{end+1}='FIGURE CAPTIONS — VsPredict_Geoenergy_v4';
lines{end+1}=repmat('=',1,55);
lines{end+1}=sprintf('Run: %s | Seed: %d',run.id,run.cfg.seeds.canonical);
lines{end+1}=sprintf('Deploy: %s (R2_WA=%.4f)',run.deploy_name,run.deploy_r2_WA);
lines{end+1}='';

caps={
'FIG01',sprintf(['Study design and leakage-controlled validation framework. '...
    'Well-A (n=%d rows) is the calibration well, split by depth (training n=%d, internal test n=%d). '...
    'Cross-well overlap of %d/%d rows (%.1f%%) in Well-B Segment 1 is excluded from all blind metrics. '...
    'Well-B Segment 0 (n=%d rows) is the independent blind-validation interval. '...
    'Primary evaluation mask (Pop-B): n=%d after Vp/Vs quality-control gate. '...
    'Model selection uses Well-A only; blind evaluation is strictly post-hoc.'],...
    height(run.T_A_raw),run.n_train,run.n_test,...
    run.overlap.n_overlap,height(run.T_B_raw),run.overlap.pct_overlap,...
    run.n_seg0,run.n_pop_B);

'FIG02',sprintf(['Well-log depth tracks for Well-A (blue, calibration) and Well-B (red/grey, blind). '...
    'The %.1f-m gap separates Segment 0 (primary blind, red) from Segment 1 (overlap, grey, n=%d). '...
    'Red circles in the V_S track: %d Vp/Vs-flagged samples (Vp/Vs < sqrt(2)). '...
    'Dashed line: train/test boundary at %.0f m.'],...
    run.cfg.depth.wellB_seg1_min-run.cfg.depth.wellB_seg0_max,...
    run.n_seg1,run.n_seg0-run.n_pop_B,run.T_A_raw.DEPTH(run.n_train));

'FIG03',['Probability density distributions of GR (a), DT (b), NPHI (c), RHOB (d) '...
    'for Well-A (blue) and Well-B Segment 0 (red). Dashed lines: well means. '...
    'Inset: standardized mean shift z and OOD fraction |z|>3. '...
    'DT exhibits severe covariate shift (z=+7.85sigma, 100% OOD); '...
    'GR, NPHI, RHOB show mild to moderate shifts.'];

'FIG04',sprintf(['Model development and Well-A-only selection. '...
    '(a) OOF R² per fold (seed=%d, k=%d) for base learners. '...
    '(b) Meta-learner Well-A internal test R²; %s selected (R²=%.4f). '...
    'Well-B was NOT used for model selection.'],...
    run.cfg.seeds.canonical,run.n_folds,run.deploy_name,run.deploy_r2_WA);

'FIG05',sprintf(['Canonical consistency and multi-seed status. '...
    'Canonical result is seed=%d from the OOF loop (no separate retraining). '...
    'Cross-run reproducibility confirmed: two independent runs produce identical results '...
    'to 4 decimal places (Gate 15 = PASS). Multi-seed aggregation is a stub; '...
    'per-seed OOF metrics are available in OOF_fold_metrics.csv.'],run.cfg.seeds.canonical);

'FIG06',sprintf(['Blind-well evaluation of the Well-A-selected deployment model (%s, seed=%d). '...
    '(a) Predicted versus measured V_S; 1:1 line and +/-RMSE bounds. '...
    '(b) Residual (predicted - measured) versus depth. '...
    '(c) Residual histogram; dashed line: mean bias. '...
    'Metrics from Pop-B (physical-QC mask, n=%d, Vp/Vs >= sqrt(2)): '...
    'R²=%.4f, RMSE=%.4f km/s, bias=%+.4f km/s. '...
    'Systematic positive bias indicates prediction collapse toward the calibration-domain range.'],...
    upper(run.deploy_name),run.cfg.seeds.canonical,run.eval_popB.n,...
    run.eval_popB.R2_raw,run.eval_popB.RMSE_raw,run.eval_popB.bias_raw);

'FIG07',sprintf(['Cross-domain diagnostic summary. '...
    '(a) Prediction bias for all models; empirical baselines show negative bias, '...
    'ML models show positive bias, indicating distinct failure modes. '...
    '(b) Well-A internal R² versus Well-B blind R² for meta-learner candidates; '...
    '%s has the highest Well-A R² (%.4f) but does not achieve the least-negative blind R². '...
    'All blind R² < 0: generalization failure confirmed for both evaluation populations.'],...
    run.deploy_name,run.deploy_r2_WA);

'FIG08',sprintf(['Geomechanical consequence of prediction collapse. '...
    '(a) Measured Vp/Vs (blue) and predicted Vp/Vs (red dashed); '...
    'dashed line: physical minimum sqrt(2)=1.414. '...
    '(b) Physical-gate counts. (c) Diagnostic summary. '...
    '%s predictions yield V_S in the calibration range while V_P in Well-B Segment 0 '...
    'is substantially higher, causing Vp/Vs_pred < sqrt(2) for all %d evaluation samples. '...
    '%d/%d Poisson ratios are physically admissible (%.1f%%). '...
    'No valid dynamic elastic moduli can be derived.'],...
    upper(run.deploy_name),run.eval_popB.n,...
    run.geomech.n_nu_pred_ok,run.geomech.n_eval,run.geomech.valid_pct);
};

for ci=1:2:numel(caps)
    lines{end+1}=sprintf('%s. %s',caps{ci},caps{ci+1});
    lines{end+1}='';
end

fid=fopen(fullfile(out,'FIGURE_CAPTIONS.txt'),'w');
for li=1:numel(lines); fprintf(fid,'%s\n',lines{li}); end
fclose(fid);
fprintf('  [CAP] FIGURE_CAPTIONS.txt\n');
end
